name: "Feature request"
description: Request new functionality
title: "[Feature request]: "
labels: [
  "enhancement", 
  "pending review"
]
assignees: 
- russbiggs

body:
  - type: textarea
    id: description
    attributes:
      label: "Description of feature or enhancement"
      description: Please provide a detailed description of the feature or enhancement you would like to see in the package.
      placeholder: "..."
    validations:
        required: true
  - type: checkboxes
    id: pr
    attributes:
      label: Contribute a PR
      description: If approved, are you willing to submit a PR for this feature? (Not required but contributions can help expedite the process)
      options:
        - label: I would be able to submit a PR
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/openaq/.github/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true