# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
on:
    push:
      branches: [main]
    pull_request:

name: lint.yaml
  
permissions: read-all
  
jobs:
    lint:
        if: "!contains(github.event.head_commit.message, 'lintr skip')"
        runs-on: ubuntu-latest
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        steps:
        - uses: actions/checkout@v4

        - uses: r-lib/actions/setup-r@v2
          with:
            use-public-rspm: true

        - uses: r-lib/actions/setup-r-dependencies@v2
          with:
            extra-packages: any::lintr, local::.
            needs: lint

        - name: Lint
          run: lintr::lint_package()
          shell: Rscript {0}
          env:
            LINTR_ERROR_ON_LINT: true